name: angular2_example
environment:
  sdk: '>=1.4.0'
dependencies:
  angular2: '>=2.0.0-alpha.1 <3.0.0'
  browser: '>=0.10.0+2 <0.11.0'
dev_dependencies:
  guinness: ">=0.1.16 <0.2.0"
transformers:
  - $dart2js:
      minify: true
      commandLineOptions: [--trust-type-annotations, --trust-primitives, --dump-info]